//! Request and response types for OSS operations.

pub mod common;
pub mod request;
pub mod response;

pub use common::{
    BucketAcl, BucketName, CorsHttpMethod, MetadataDirective, ObjectAcl, ObjectKey, Region,
    ServerSideEncryption, StorageClass, VersioningStatus,
};
pub use request::{
    AbortMultipartUploadRequest, AbortMultipartUploadRequestBuilder, AppendObjectRequest,
    AppendObjectRequestBuilder, CompleteMultipartUploadRequest,
    CompleteMultipartUploadRequestBuilder, CompleteMultipartUploadXml, CompletedPart,
    CopyObjectRequest, CopyObjectRequestBuilder, CorsRule, CreateBucketRequest,
    CreateBucketRequestBuilder, DeleteBucketCorsRequest, DeleteBucketCorsRequestBuilder,
    DeleteBucketEncryptionRequest, DeleteBucketEncryptionRequestBuilder,
    DeleteBucketLifecycleRequest, DeleteBucketLifecycleRequestBuilder, DeleteBucketLoggingRequest,
    DeleteBucketLoggingRequestBuilder, DeleteBucketPolicyRequest, DeleteBucketPolicyRequestBuilder,
    DeleteBucketRequest, DeleteBucketRequestBuilder, DeleteMultipleObjectsRequest,
    DeleteMultipleObjectsRequestBuilder, DeleteObjectRequest, DeleteObjectRequestBuilder,
    DeleteObjectTaggingRequest, DeleteObjectTaggingRequestBuilder, GetBucketAclRequest,
    GetBucketAclRequestBuilder, GetBucketCorsRequest, GetBucketCorsRequestBuilder,
    GetBucketEncryptionRequest, GetBucketEncryptionRequestBuilder, GetBucketInfoRequest,
    GetBucketInfoRequestBuilder, GetBucketLifecycleRequest, GetBucketLifecycleRequestBuilder,
    GetBucketLocationRequest, GetBucketLocationRequestBuilder, GetBucketLoggingRequest,
    GetBucketLoggingRequestBuilder, GetBucketPolicyRequest, GetBucketPolicyRequestBuilder,
    GetBucketVersioningRequest, GetBucketVersioningRequestBuilder, GetObjectAclRequest,
    GetObjectAclRequestBuilder, GetObjectRequest, GetObjectRequestBuilder, GetObjectTaggingRequest,
    GetObjectTaggingRequestBuilder, HeadObjectRequest, HeadObjectRequestBuilder,
    InitiateMultipartUploadRequest, InitiateMultipartUploadRequestBuilder, LifecycleExpiration,
    LifecycleRule, LifecycleRuleStatus, LifecycleTransition, ListBucketsRequest,
    ListBucketsRequestBuilder, ListMultipartUploadsRequest, ListMultipartUploadsRequestBuilder,
    ListObjectsV2Request, ListObjectsV2RequestBuilder, ListPartsRequest, ListPartsRequestBuilder,
    PresignedUrlRequest, PresignedUrlRequestBuilder, PutBucketAclRequest,
    PutBucketAclRequestBuilder, PutBucketCorsRequest, PutBucketCorsRequestBuilder,
    PutBucketEncryptionRequest, PutBucketEncryptionRequestBuilder, PutBucketLifecycleRequest,
    PutBucketLifecycleRequestBuilder, PutBucketLoggingRequest, PutBucketLoggingRequestBuilder,
    PutBucketPolicyRequest, PutBucketPolicyRequestBuilder, PutBucketVersioningRequest,
    PutBucketVersioningRequestBuilder, PutObjectAclRequest, PutObjectAclRequestBuilder,
    PutObjectRequest, PutObjectRequestBuilder, PutObjectTaggingRequest,
    PutObjectTaggingRequestBuilder, RestoreObjectRequest, RestoreObjectRequestBuilder,
    UploadPartRequest, UploadPartRequestBuilder,
};
pub use response::{
    AbortMultipartUploadResponse, AccessControlList, AppendObjectResponse, BucketAccessControlList,
    BucketInfo, BucketInfoDetail, BucketOwner, BucketsContainer, CommonPrefix,
    CompleteMultipartUploadResponse, CopyObjectResponse, CorsRuleResponse, CreateBucketResponse,
    DeleteBucketCorsResponse, DeleteBucketEncryptionResponse, DeleteBucketLifecycleResponse,
    DeleteBucketLoggingResponse, DeleteBucketPolicyResponse, DeleteBucketResponse,
    DeleteMultipleObjectsResponse, DeleteObjectResponse, DeleteObjectTaggingResponse,
    DeletedObject, EncryptionRuleResponse, GetBucketAclResponse, GetBucketCorsResponse,
    GetBucketEncryptionResponse, GetBucketInfoResponse, GetBucketLifecycleResponse,
    GetBucketLocationResponse, GetBucketLoggingResponse, GetBucketPolicyResponse,
    GetBucketRefererResponse, GetBucketVersioningResponse, GetObjectAclResponse, GetObjectResponse,
    GetObjectTaggingResponse, HeadObjectResponse, InitiateMultipartUploadResponse,
    LifecycleExpirationResponse, LifecycleRuleResponse, LifecycleTransitionResponse,
    ListBucketsResponse, ListMultipartUploadsResponse, ListObjectsV2Response, ListPartsResponse,
    LoggingEnabled, MultipartUploadInfo, ObjectAccessControlList, ObjectBody, ObjectInfo, PartInfo,
    PutBucketAclResponse, PutBucketCorsResponse, PutBucketEncryptionResponse,
    PutBucketLifecycleResponse, PutBucketLoggingResponse, PutBucketPolicyResponse,
    PutBucketRefererResponse, PutBucketVersioningResponse, PutObjectAclResponse, PutObjectResponse,
    PutObjectTaggingResponse, RefererBlacklist, RefererList, RestoreObjectResponse, Tag, TagSet,
    UploadPartResponse,
};
